{
    "name" : "Librery Management system",
    "version":"1.0",
    "author": "Vaishnavi patil",
    "sequence":10,
    "license":"LGPL-3",
    "application":True,
    "installable":True,
    "depends": [
            "base","mail","account","stock","hr"
    ],
    "data": [
        "security/ir.model.access.csv",
        "wizards/book_reservation_view.xml",
        "wizards/magazine_frequency_view.xml",
        #"data/author_view.xml",
        "data/sequence_data.xml",
        "data/schedule_action.xml",
        "data/mail_template_data.xml",
        "views/books_view.xml",
        "views/members_view.xml",
        "views/borrow_view.xml",
        "views/category_view.xml",
        "views/fines_view.xml",
        "views/authors_view.xml",
        "views/magzine_view.xml",
        "views/res_config_settings_view.xml",
        "views/publisher_view.xml",
        "views/reservation_view.xml",
        "views/employee_view.xml",
        "reports/report.xml",
        "reports/library_card.xml",
        "reports/publisher_report.xml",
        "reports/publisher_card.xml"
    ],
     'images': ['static/description/icon.png'],
}