{
    "name": "Librery Management system",
    "version": "1.0",
    "author": "Vaishnavi patil",
    "sequence": 10,
    "license": "LGPL-3",
    "application": True,
    "installable": True,
    "depends": [
        "base", "mail", "account", "stock", "hr", "sale", "board", "website"
    ],
    "data": [
        "security/ir.model.access.csv",
        "security/security.xml",
        "wizards/book_reservation_view.xml",
        "wizards/magazine_frequency_view.xml",
        "wizards/layouts_wizard.xml",
        # "data/author_view.xml",
        "data/sequence_data.xml",
        "data/schedule_action.xml",
        "data/mail_template_data.xml",
        "data/report_layout.xml",
        "views/books_view.xml",
        "views/members_view.xml",
        "views/borrow_view.xml",
        "views/category_view.xml",
        "views/fines_view.xml",
        "views/authors_view.xml",
        "views/magzine_view.xml",
        "views/res_config_settings_view.xml",
        "views/publisher_view.xml",
        "views/reservation_view.xml",
        "views/employee_view.xml",
        "views/dashboard.xml",
        "views/website_template.xml",
        "views/book_review.xml",
        "reports/report.xml",
        "reports/library_card.xml",
        "reports/publisher_report.xml",
        "reports/publisher_card.xml",
        "reports/ir_action_report.xml",
        "reports/ir_actions_report_template.xml",
        "reports/report_template.xml",
        "reports/sale_report_inherit.xml",
        "reports/book_report_views.xml",
    ],
    'images': ['static/description/icon.png'],
}
